name: Publish to npm

on:
  push:
    tags:
      - 'v*' # vから始まるタグに反応

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # checkoutアクションのために必要
      id-token: write # npmへの公開に必要 (provenanceを使用する場合)
    steps:
      - uses: actions/checkout@v6
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: '22'
          cache: true
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: vp install

      - name: Build
        run: vp pack

      - name: Publish to npm
        run: npx --yes npm@11.12.1 publish --provenance --access public
